### ISSUE TITLE
runserver了 报错ImportError: No module named urls

### ISSUE THREAD

**Issue by VegetableCat** [evilbinary/myblog#7]
本机：debian8
runserver后 
浏览器访问127.0.0.1:8000显示'A server error occurred.  Please contact the administrator.'
同时 shell中抛出异常 ImportError: No module named urls

请问我该怎么做呢

**Comment by evilbinary** [comment]
是否下载齐全了代码。

**Comment by evilbinary** [comment]
ROOT_URLCONF  urls.py路径在 settings.py.是否正确。

**Comment by topicgit** [comment]
系统: CentOS release 6.6 x86_64
python: 2.7.10
浏览器访问: A server error occurred.  Please contact the administrator.
shell抛出异常:
`[10/Oct/2016 18:17:54] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.10/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/root/.pyenv/versions/blog22/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/root/.pyenv/versions/blog22/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/core/handlers/base.py", line 190, in get_response
    resolver, sys.exc_info())
  File "/root/.pyenv/versions/blog22/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/core/handlers/base.py", line 239, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/root/.pyenv/versions/blog22/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/root/.pyenv/versions/2.7.10/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/blog/myblog/wsgi/mysite/mysite/urls.py", line 19, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "/root/.pyenv/versions/blog22/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.pyenv/versions/2.7.10/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls`
请问应该怎么解决？

**Comment by evilbinary** [comment]
django 安装不完整？

**Comment by topicgit** [comment]
是根据setup.py安装的，安装是成功的。
url(r'^ckeditor/', include('ckeditor.urls'))
我看到在myblog/wsgi/mysite目录下并没有cheditor的目录，有blog的目录，是否没上传cheditor目录的py代码？

**Comment by evilbinary** [comment]
ckeditor 是依赖，应该自动安装。

**Comment by Landius** [comment]
我也出现了这个问题，win7，python2.7 64bit，没有安装 pysqlite，这个应该没影响吧

**Comment by evilbinary** [comment]
@Landius 对的，你安装一下pip install pysqlite

**Comment by Landius** [comment]
@evilbinary 貌似并不是 pysqlite 的问题，我在
`Lib\site-packages\django_ckeditor-5.2.1-py2.7.egg\ckeditor`
目录下添加了一个 `urls.py` 就可以正常访问了

**Comment by Landius** [comment]
@evilbinary 原来是 ckeditor 版本的问题（年代过于久远了吗）我的解决方法如下

1. 在 `setup.py` 将 `django_editor` 改为 `django_editor==4.0.2`

2. `cd ./myblog/wsgi/mysite` 然后 `mkdir media && cd media && mkdir uploads`

3. 在 `setting.py` 令 `CKEDITOR_UPLOAD_PATH = os.path.join(MEDIA_ROOT, 'uploads')`

**Comment by evilbinary** [comment]
可能太多久远了。
